import "sanitize.css";
import "prismjs/themes/prism-tomorrow.css";
import "prismjs/plugins/line-numbers/prism-line-numbers.css";
import "prismjs/plugins/command-line/prism-command-line.css";
import "fontsource-montserrat/900.css";
import "fontsource-merriweather";
import "fontsource-pt-sans";
import "fontsource-fira-sans";
import "typeface-droid-sans-mono";
